name: Deploy Test
on:
  push:
    branches:
      - test

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        password: ${{ secrets.TEST_PASSWORD }}
        port: ${{ secrets.TEST_PORT }}
        server-dir: /

    - name: 📂 Install dependencies
      run: yarn
